version: '3.9'

x-variables:
  flag_initial_cluster_token: &flag_initial_cluster_token '--initial-cluster-token=sup3rs3kritt0ken'
  common_settings: &common_settings
    image: quay.io/coreos/etcd:v3.5.12
    restart: unless-stopped
    entrypoint: /usr/local/bin/etcd

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    network_mode: service:devcontainer

  etcd-1:
    <<: *common_settings
    command:
      - '--name=etcd-1'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://localhost:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster-state=new'
      - *flag_initial_cluster_token
    volumes:
      - etcd1:/etcd_data
    network_mode: service:devcontainer

volumes:
  etcd1:
