version: '3.9'

x-variables:
  flag_initial_cluster_token: &flag_initial_cluster_token '--initial-cluster-token=mys3cr3ttok3n'
  common_settings: &common_settings
    image: quay.io/coreos/etcd:v3.5.12
    restart: unless-stopped
    entrypoint: /usr/local/bin/etcd

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached

    # Runs app on the same network as the redis container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:redis

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  etcd-1:
    <<: *common_settings
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
      - *flag_initial_cluster_token
    volumes:
      - etcd1:/etcd_data
    ports:
      - '2379:2379'

  etcd-2:
    <<: *common_settings
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
      - *flag_initial_cluster_token
    volumes:
      - etcd2:/etcd_data

  etcd-3:
    <<: *common_settings
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
      - *flag_initial_cluster_token
    volumes:
      - etcd3:/etcd_data

volumes:
  etcd1:
  etcd2:
  etcd3:
