version: '3.9'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached

    # Runs app on the same network as the redis container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:redis

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
